logoText = "风陵" 
logoType = "short" # long, short
description = "风陵" 
version="0.08"
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""
custom_css = ["css/custom.css"]
custom_js =["sw.js"] 
themeOptions = ["light","kimbie","dark", "hacker", "solarized"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
#随机一句调用接口
daytalks =  "https://cdn.jsdelivr.net/gh/Tyningling/cdn/0.09/js/say.js"
siteCDN = "https://cdn.jsdelivr.net/gh/Tyningling/cdn/0.09" #CDN调用
viewportSize = "wide" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false

# header
homeHeaderType = "text" # text, img, slide

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2020"
pubPaginate = 20

# whoami
myname = "风陵"
email = "w2638301509@gmail.com"
whoami = "A Student |  Java Dev"
bioImageUrl = ""
useGravatar = false
location = "SZ | CHINA"
organization = "SuffocationRoom"
link = "https://inkhin.com/"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "left"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org

[valine]
  enable =true
  appId = 'zyYEfn2X9xCTgUpH1QPJ76x5-gzGzoHsz'
  appKey = 'OuYLCACD7WsEdKbzGnWz54rf'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '说点什么吧...'
  visitor = false

[socialOptions]
  github = "https://github.com/tyningling"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
  name = "telegram"
[[share]]
  name = "weibo"
[[share]]
  name = "line"
[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""